[workspace]
resolver = "3"
members = ["microsoft_auth"]

[package]
name = "fastmc"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version="0.14.0", features = ["svg"]}
microsoft_auth = {path = "./microsoft_auth"}
