[package]
name = "microsoft_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
oauth2 = { version = "4.4", default-features = false, features = ["reqwest"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["time"] }
