[package]
name = "fastmc_config"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.10"
thiserror = "1.0"
